# Transforms

This is taking the data and putting it into the processed forms for the models (e.g. text to numbers or more speciically tensors). 

- `transform`: modify the features (x)
- `target_transform`: modify the labels (y)

The [`torchvision.transforms`](https://docs.pytorch.org/vision/stable/transforms.html) module offers several commonly-used transforms out of the box.


In [1]:
import os

import numpy as np
import torch
from torchvision import datasets
from torchvision.transforms import Lambda, ToTensor


In [2]:
%load_ext watermark

# Load data

The FashionMNIST features are in PIL Image format, and the labels are integers. We want:
- features: PIL Image format > normalized tensors
- labels: integers > one-hot encoded tensors

Normalized tensor: Values have been scaled, typically to 0 and 1 (i.e. not a unit vector but provides some similar advantages practically). This supports:
- training stability: inputs are in smaller, more consistent ranges
- gradient flow: helps prevent vanishing/exploding gradients (gradient can shrink or explode across layers, leading to later layers getting big/small updates, respectively)
- optimization efficiency: loss landscape is smoother for optimizers

In [33]:
del ds

In [34]:
DATA_DIR="../local_data/transformer-mentor_data"

ds = datasets.FashionMNIST(
    root=DATA_DIR,
    train=True,
    download=False,
    transform=ToTensor(),
    # target_transform=Lambda(lambda y: torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(y), value=1))
)


Let's focus on the above uses of `ToTensor()` and `Lambda`.

# `ToTensor()`

Converts a PIL image or NumPy `ndarray` to a `FloatTensor` and scales the image's pixel intensity values in the range `[0., 1.]`.

# Lambda Transforms

Allows for user-defined lambda functions. In this example, here's a way to turn the integers into a one-hot-encoded tensor in the following way:
- create a zero tensor of size 10 (number of labels)
- call `scatter_1` which assigns a `value=1` on the index as given by the label `y`

This was already applied in the above example.

In [35]:
ds.targets

tensor([9, 0, 0,  ..., 3, 0, 5])

In [16]:
y = ds.targets[0:10]
y

tensor([9, 0, 0, 3, 0, 2, 7, 2, 5, 5])

In [17]:
torch.zeros(10, dtype=torch.float)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(y[0]), value=1)

/tmp/ipykernel_96706/845930082.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(y[0]), value=1)


tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [4]:
%watermark

Last updated: 2025-08-16T16:10:40.267800+00:00

Python implementation: CPython
Python version       : 3.12.11
IPython version      : 9.4.0

Compiler    : GCC 12.2.0
OS          : Linux
Release     : 6.10.14-linuxkit
Machine     : aarch64
Processor   : 
CPU cores   : 7
Architecture: 64bit



In [5]:
%watermark -iv

torchvision: 0.22.1
torch      : 2.7.1
numpy      : 2.3.1

